### ISSUE TITLE
can't access property "content", Object(...)(...) is null

### ISSUE THREAD

**Issue by saschanaz** [hahnlee/hwp.js#12]
https://www.grac.or.kr/Board/Inform.aspx?bno=660&type=view&pageindex=0 에서 받은 파일을 데모 페이지에서 열면 제목과 같은 오류가 발생합니다. 이번에는 콘솔에 에러 스택이 안 뜨네요 👀

**Comment by hahnlee** [comment]
배포용 문서가 아닌데도 열리지 않는군요. 확인하였습니다.
주말중으로 더 확인해보도록 하겠습니다.

**Comment by hahnlee** [comment]
https://oss.sheetjs.com/cfb-editor/#/cfb-editor/
cfb-editor로 확인해본 결과 10번째 이미지는 jpg지만 레코드상에는 png로 기록되어 있음 조사필요

**Comment by hahnlee** [comment]
그외에 추가적인 문제가 보여 더 시간이 걸릴것 같습니다.

**Comment by hahnlee** [comment]
@saschanaz 데모페이지에서 열어보시면 이제 보이실겁니다.

**Comment by saschanaz** [comment]
감사합니다, 확인했습니다! 주석을 보니 스펙 문서가 정말 문제가 있나 보네요...

**Comment by hahnlee** [comment]
제가 잘못이해했거나 트리구조로 파싱할때 잘못했을 가능성이 있어 아직 단정짓긴 어렵습니다.

그래도 현 상황에선 이게 가장 최적의 결과물을 만드는 설정으로 보입니다
