### ISSUE TITLE
Inoperative case report

### ISSUE THREAD

**Issue by lucaskim1233** [hahnlee/hwp.js#17]
I tried to open [this hwp](http://www.korea.kr/common/download.do?fileId=191880328&tblKey=GMN) document but failed.
Not sure it is valid document but need to show any message if it cannot be opened.

P.S. I'm a big fan of your work:+1:

**Comment by hahnlee** [comment]
Thanks for reporting this problem.

![266477DD-3661-4594-8D27-01FDF0C20EBB](https://user-images.githubusercontent.com/16930958/92850889-eae50180-f427-11ea-9b6c-e9e94614da55.png)

But in my device, It rebdered well.

Could you give me other information such as browser or os information?

PS. If you use the Chrome extension, the current version has a problem, so look forward to the next update.

**Comment by hahnlee** [comment]
@lucaskim1233 Any update on this?

**Comment by lucaskim1233** [comment]
My test environment was Chrome.
I've just tested the document on the [demo page](https://hanlee.io/hwp.js/demo/) and it worked fine.
Thanks you for the response.
I'm waiting for the next update of the Chrome extension ;)

**Comment by hahnlee** [comment]
@lucaskim1233 Thanks for the response.
This issue may resolved version 1.1 and, latest web store version is also 1.1.
Please check update :)
