### ISSUE TITLE
[Typo] /src/parser/DotInfoParser.ts

### ISSUE THREAD

**Issue by sboh1214** [hahnlee/hwp.js#29]
Probably It's a useless issue, but I found that there is a typo in your source code file.

[/src/parser/DotInfoParser.ts](https://github.com/hahnlee/hwp.js/blob/153a020c8a89ac83806f7572e05fc967243f1ce2/src/parser/DotInfoParser.ts#L33)

I think it should be DotInfoParser.ts --> DocInfoParser.ts
Thanks

**Comment by hahnlee** [comment]
Thanks for the reporting. Can you make a PR on this issue?

**Comment by sboh1214** [comment]
I uploaded pull request #30 Thanks!

**Comment by hahnlee** [comment]
Checked! Thanks again :D
